{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMyfPfxoy8dxQyRJXEN0ZIA"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "71B_GETH1Z4z"
      },
      "outputs": [],
      "source": [
        "sair = False\n",
        "\n",
        "while sair == False:\n",
        "    print(\"=-==-==-==-==-= Menu de Opções =-==-==-==-==-=\")\n",
        "\n",
        "    print('''\n",
        "        [1] Criar uma lista:\n",
        "        [2] Calculadora:\n",
        "        [3] Conversor\n",
        "        [4]\n",
        "        ''')\n",
        "\n",
        "    Op = int(input(\"Escolha uma opção: \"))\n",
        "\n",
        "    if Op == 1:\n",
        "        Lista = []\n",
        "        Itens = int(input(\"Quantidade de itens na lista: \"))\n",
        "        for i in range(Itens):\n",
        "            x = input(\"Item: \")\n",
        "            Lista.append(x)\n",
        "        print(Lista)\n",
        "\n",
        "        z = input(\"Deseja continuar? \")\n",
        "        if z == 'n':\n",
        "            print(\"Finalizado...\")\n",
        "            sair = True\n",
        "\n",
        "\n",
        "    elif Op == 2:\n",
        "        # int transforma string em número inteiro\n",
        "        num1 = int(input(\"Digite um número: \"))\n",
        "        operador = input(\n",
        "            \"Digite o operador (+(soma),-(subtração),/(divisão),*(multiplicação),**(elevado), */(Raiz Quadrada), /*(Raiz Cúbica): \")\n",
        "\n",
        "    # */ Raiz Quadrada\n",
        "        if operador == \"*/\":\n",
        "            print(\"A raiz quadrada de {} é {}\".format(num1, (num1 ** 0.5)))\n",
        "    # */ Raiz Cúbica\n",
        "        elif operador == \"/*\":\n",
        "            print(\"A raiz cúbica de {} é {}\".format(num1, (num1 ** 1/3)))\n",
        "    # + soma\n",
        "        elif operador == \"+\":\n",
        "            num2 = int(input(\"Digite outro número: \"))\n",
        "            print(\"A soma entre {} e {} é {}\".format(num1, num2, (num1 + num2)))\n",
        "    # - subtração\n",
        "        elif operador == \"-\":\n",
        "            num2 = int(input(\"Digite outro número: \"))\n",
        "            print(\"A subtração entre {} e {} é {}\".format(num1, num2, (num1 - num2)))\n",
        "    # / divisão\n",
        "        elif operador == \"/\":\n",
        "            num2 = int(input(\"Digite outro número: \"))\n",
        "            print(\"A divisão entre {} e {} é {}\".format(num1, num2, (num1 / num2)))\n",
        "    # * multiplicação\n",
        "        elif operador == \"*\":\n",
        "            num2 = int(input(\"Digite outro número: \"))\n",
        "            print(\"A multiplicação entre {} e {} é {}\".format(num1, num2, (num1 * num2)))\n",
        "    # ** Elevado\n",
        "        elif operador == \"**\":\n",
        "            num2 = int(input(\"Digite outro número: \"))\n",
        "            print(\"O número {} elevado a {} é {}\".format(num1, num2, (num1 ** num2)))\n",
        "\n",
        "        z = input(\"Deseja continuar? \")\n",
        "        if z == 'n':\n",
        "            print(\"Finalizado...\")\n",
        "            sair = True\n",
        "\n",
        "    elif Op == 3:\n",
        "\n",
        "        print('''\n",
        "                [1] Distância\n",
        "                [2] Peso\n",
        "                ''')\n",
        "\n",
        "        converter = int(input(\"O que deseja conveter? \"))\n",
        "\n",
        "        if converter == 1:\n",
        "            print('''\n",
        "                [1] Quilômetro (km)\n",
        "                [2] Hectômetro (hm)\n",
        "                [3] Decâmetro (dam)\n",
        "                [4] Metro (m)\n",
        "                [5] Decâ­metro (dm)\n",
        "                [6] Centi­metro (cm)\n",
        "                [7] Mili­metro (mm)\n",
        "                ''')\n",
        "\n",
        "            op1 = input('Unidade a ser convertida: ')\n",
        "            op2 = input('Unidade para conversão: ')\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= KM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# KM p/ HM\n",
        "\n",
        "            if op1 == 'km' and op2 == 'hm':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em hectômetros são {} hm\".format(q, (q * 10)))\n",
        "\n",
        "# KM p/ DAM\n",
        "\n",
        "            elif op1 == 'km' and op2 == 'dam':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em decâmetros são {} dm\".format(q, (q * 100)))\n",
        "\n",
        "# KM p/ M\n",
        "\n",
        "            elif op1 == 'km' and op2 == 'm':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em metros são {} m\".format(q, (q * 1000)))\n",
        "\n",
        "# KM p/ DM\n",
        "\n",
        "            elif op1 == 'km' and op2 == 'dm':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em decâ­metros são {} dm\".format(q, (q * 10000)))\n",
        "\n",
        "# KM p/ CM\n",
        "\n",
        "            elif op1 == 'km' and op2 == 'cm':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em centi­metros são {} cm\".format(q, (q * 100000)))\n",
        "\n",
        "# KM p/ MM\n",
        "\n",
        "            elif op1 == 'km' and op2 == 'mm':\n",
        "                q = float(input('Valor: '))\n",
        "                m = print(\"{} km em mili­metros são {} mm\".format(q, (q * 1000000)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= HM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# HM p/ KM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'km':\n",
        "                q = float(input('Valor hm: '))\n",
        "                m = print(\"{} hm em quilômetros são {} km\".format(q, (q / 10)))\n",
        "\n",
        "# HM p/ DAM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'dam':\n",
        "                q = int(input('Valor hm: '))\n",
        "                m = print(\"{} hm em decâmetros são {} dam\".format(q, (q * 10)))\n",
        "\n",
        "# HM p/ M\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'm':\n",
        "                q = int(input('Valor hm: '))\n",
        "                m = print(\"{} hm em metros são {} m\".format(q, (q * 100)))\n",
        "\n",
        "# HM p/ DM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'dm':\n",
        "                q = int(input('Valor hm: '))\n",
        "                m = print(\"{} hm em decâ­metros são {} dm\".format(q, (q * 1000)))\n",
        "\n",
        "# HM p/ CM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'cm':\n",
        "                q = int(input('Valor hm: '))\n",
        "                m = print(\"{} hm em centi­metros são {} cm\".format(q, (q * 10000)))\n",
        "\n",
        "# HM p/ MM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'mm':\n",
        "                q = int(input('Valor hm: '))\n",
        "                m = print(\"{} hm em milimetros são {} mm\".format(q, (q * 1000000)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= DAM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# DAM p/\n",
        "\n",
        "            elif op1 == 'dam' and op2 == 'km':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print(\"{} dam em quilômetros são {} km\".format(q, (q / 100)))\n",
        "\n",
        "# DAM p/ HM\n",
        "            elif op1 == 'dam' and op2 == 'hm':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print('{} dam em hectômetros são {} hm'.format(q, (q / 10)))\n",
        "\n",
        "# DAM p/ M\n",
        "\n",
        "            elif op1 == 'dam' and op2 == 'm':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print('{} dam em metros são {} m'.format(q, (q * 10)))\n",
        "\n",
        "# DAM p/ DM\n",
        "\n",
        "            elif op1 == 'dam' and op2 == 'dm':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print(\"{} dam em decâ­metros são {} dm\".format(q, (q * 100)))\n",
        "\n",
        "# DAM p/ CM\n",
        "\n",
        "            elif op1 == 'dam' and op2 == 'cm':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print('{} dam em centi­metros são {} cm'.format(q, (q * 1000)))\n",
        "\n",
        "# DAM p/ MM\n",
        "\n",
        "            elif op1 == 'dam' and op2 == 'mm':\n",
        "                q = int(input('Valor dam: '))\n",
        "                m = print('{} dam em mili­metros são {}'.format(q, (q * 10000)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= M =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# M p/ KM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'km':\n",
        "                q = float(input('Valor m: '))\n",
        "                m = print('{} m em quilômetros são {} km'.format(q, (q / 1000)))\n",
        "\n",
        "# M p/ HM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'hm':\n",
        "                q = float(input('Valor m: '))\n",
        "                m = print('{} m em hectômetros são {} hm'.format(q, (q / 100)))\n",
        "\n",
        "# M p/ DAM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'dam':\n",
        "                q = float(input('Valor m: '))\n",
        "                m = print('{} m em decâmetros são {} dam'.format(q, (q / 10)))\n",
        "\n",
        "# M p/ DM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'dm':\n",
        "                q = float(input('Valor em metros: '))\n",
        "                m = print('{} m em deci­metros são {} dm'.format(q, (q * 10)))\n",
        "\n",
        "\n",
        "# M p/ CM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'cm':\n",
        "                q = float(input('Valor em metros: '))\n",
        "                m = print('{} m em centi­metros são {} cm'.format(q, (q * 100)))\n",
        "\n",
        "# M p/ MM\n",
        "\n",
        "            elif op1 == 'm' and op2 == 'mm':\n",
        "                q = float(input('Valor em metros: '))\n",
        "                m = print('{} m em mili­metros são {} mm'.format(q, (q * 1000)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= DM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# DM p/ KM\n",
        "\n",
        "            elif op1 == 'dm' and op2 == 'km':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('{} dm em quilômetros são {} km'.format(q, (q / 10000)))\n",
        "\n",
        "# DM p/ HM\n",
        "\n",
        "            elif op1 == 'dm' and op2 == 'hm':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('{} dm em decâ­metros são {} hm'.format(q, (q / 1000)))\n",
        "\n",
        "# DM p/ DAM\n",
        "\n",
        "            elif op1 == 'hm' and op2 == 'dam':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('{} dm em decimetros são {} dam'.format(q, (q / 100)))\n",
        "\n",
        "# DM p/ M\n",
        "\n",
        "            elif op1 == 'dm' and op2 == 'm':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('{} dm em metros são {} m'.format(q, (q / 10)))\n",
        "\n",
        "# DM p/ CM\n",
        "\n",
        "            elif op1 == 'dm' and op2 == 'cm':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('{} dm em centi­metros são {} cm'.format(q, (q * 10)))\n",
        "\n",
        "# DM p/ MM\n",
        "\n",
        "            elif op1 == 'dm' and op2 == 'mm':\n",
        "                q = float(input('Valor em deci­metros: '))\n",
        "                m = print('Â´{} dm em mili­metros são {} mm'.format(q, (q * 100)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= CM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# CM p/ KM\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'km':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em quilômetros são {} km'.format(q, (q / 100000)))\n",
        "\n",
        "# CM p/ HM\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'hm':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em hectômetros são {} hm'.format(q, (q / 10000)))\n",
        "\n",
        "# CM p/ DAM\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'dam':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em decimetros são {} dam'.format(q, (q / 1000)))\n",
        "\n",
        "# CM p/ M\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'm':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em metros são {} m'.format(q, (q / 100)))\n",
        "\n",
        "# CM p/ DM\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'dm':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em deci­metros são {} dm'.format(q, (q / 10)))\n",
        "\n",
        "# CM p/ MM\n",
        "\n",
        "            elif op1 == 'cm' and op2 == 'mm':\n",
        "                q = float(input('Valor em centi­metros: '))\n",
        "                m = print('{} cm em mili­metros são {} mm'.format(q, (q * 10)))\n",
        "\n",
        "# =-=-=-=-=-=-=-=-=-= MM =-=-=-=-=-=-=-=-=-=-=-=-\n",
        "\n",
        "# MM p/ KM\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'km':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em quilômetros são {} km'.format(q, (q / 1000000)))\n",
        "\n",
        "# MM p/ HM\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'hm':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em hectômetros são {} hm'.format(q, (q / 100000)))\n",
        "\n",
        "# MM p/ DAM\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'dam':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em decâmetros são {} dam'.format(q, (q / 10000)))\n",
        "\n",
        "# MM p/ M\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'm':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em metros são {} m'.format(q, (q / 1000)))\n",
        "\n",
        "# MM p/ DM\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'dm':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em deci­metros são {} dm'.format(q, (q / 100)))\n",
        "\n",
        "# MM p/ CM\n",
        "\n",
        "            elif op1 == 'mm' and op2 == 'cm':\n",
        "                q = float(input('Valor em mili­metros: '))\n",
        "                m = print('{} mm em centi­metros são {} cm'.format(q, (q / 10)))\n",
        "\n",
        "\n",
        "        elif converter == 2:\n",
        "            print('''\n",
        "                [1] Quilograma (kg)\n",
        "                [2] Hectograma (hg)\n",
        "                [3] Decagrama (dag)\n",
        "                [4] Grama (g)\n",
        "                [5] Decigrama (dg)\n",
        "                [6] Centigrama (cg)\n",
        "                [7] Miligrama (mg)\n",
        "                ''')\n",
        "\n",
        "            opcao_1 = input('')\n",
        "            opcao_2 = input('')\n",
        "\n",
        "    elif Op == 4:\n",
        "      print(\"Em desenvolvimento...\")\n",
        "\n",
        "    z = input(\"Deseja continuar? Sim/ Não: \")\n",
        "    if z == 'não' or z == 'Não':\n",
        "      print(\"Finalizado...\")\n",
        "      sair = True"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "LpGyndmWrGT0"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
